name:
 Deploy Databricks


on:

 push:

  branches:

  - main



jobs:


 deploy:


  runs-on:
   ubuntu-latest


  steps:


  - name:
      Checkout code

    uses:
      actions/checkout@v4



  - name:
      Install Databricks CLI

    uses:
      databricks/setup-cli@main



  - name:
      Validate Bundle

    run:

      databricks bundle validate



  - name:
      Deploy to DEV

    env:

      DATABRICKS_HOST:
        ${{ secrets.DATABRICKS_HOST }}

      DATABRICKS_TOKEN:
        ${{ secrets.DATABRICKS_TOKEN }}


    run:

      databricks bundle deploy -t dev
